FROM continuumio/miniconda3:23.9.0-0

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install -U --no-cache-dir \
    aind-data-schema==1.1.0 \
    imbalanced-learn==0.11.0 \
    lightgbm==4.1.0 \
    mlxtend==0.23.0 \
    scikit-optimize==0.9.0 \
    seaborn==0.13.0 \
    umap-learn==0.5.4 \
    xgboost==2.0.2 \
    wavpack-numcodecs==0.2.1 \
    spikeinterface[full]==0.101.2

RUN pip install --no-cache-dir --ignore-installed scikit-learn==1.3.2
