FROM continuumio/miniconda3:23.9.0-0

ARG DEBIAN_FRONTEND=noninteractive

RUN pip install -U --no-cache-dir \
    aind-data-schema==1.1.0 \
    hdbscan==0.8.38.post1 \
    spikeinterface[full]==0.101.2 \
    torch==2.2.0
