FROM continuumio/miniconda3:23.9.0-0

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install -U --no-cache-dir \
    hdmf-zarr==0.9.0 \
    pynwb==2.8.2 \
    neuroconv==0.6.4 \
    zarr==2.17.2 \
    wavpack-numcodecs==0.2.1 \
    spikeinterface[full]==0.101.2

# SpikeInterface installation from source with an NWB fix (#3059)
RUN pip uninstall -y neuroconv && \
git clone https://github.com/catalystneuro/neuroconv.git &&  \
cd neuroconv && git checkout bfbbe4bff8245760622e5b873cd846d346c6ae06  && \
pip install --no-cache-dir . && \
cd ..
