FROM continuumio/miniconda3:23.9.0-0

ARG DEBIAN_FRONTEND=noninteractive


RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        git \
        fonts-freefont-ttf=20120503-10 \
    && rm -rf /var/lib/apt/lists/*

# correct mapping to make libvips work
ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libffi.so.7

# install libvips
RUN apt-get update \
    && apt-get install -y libvips libvips-dev libvips-tools libtiff5-dev

# install default fonts
RUN apt-get install -y fonts-freefont-ttf

# needed for motion estimation
RUN pip install --no-cache-dir torch==2.2.0

RUN pip install --no-cache-dir \
    aind-data-schema==1.1.0 \
    backports-datetime-fromisoformat==2.0.2 \
    pyvips==2.2.1 \
    wavpack-numcodecs==0.2.1 \
    pynwb==2.8.0 \
    hdmf-zarr==0.8.0 \
    spikeinterface[full,widgets]==0.101.2

RUN pip install --no-cache-dir --no-deps aind-metadata-upgrader==0.0.22
